# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Acme-ConspiracyTheory-Random`
	:runtime-requirement    [ :on "perl 5.012"^^:CpanId ];
	:runtime-requirement    [ :on "List::Util 1.54"^^:CpanId ];
	:runtime-requirement    [ :on "Exporter::Shiny 1.000000"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

